// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0GKLwsF4vZaPOJPtzLhTNDQoIYgcskto',
    appId: '1:79067367979:web:b897ec5b8fd1d3ad19386e',
    messagingSenderId: '79067367979',
    projectId: 'plato-17bc4',
    authDomain: 'plato-17bc4.firebaseapp.com',
    databaseURL: 'https://plato-17bc4-default-rtdb.firebaseio.com',
    storageBucket: 'plato-17bc4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqXssrCTnYNsY2RCqzaP4xpao27iFXqIA',
    appId: '1:79067367979:android:a5c9938d0a93241519386e',
    messagingSenderId: '79067367979',
    projectId: 'plato-17bc4',
    databaseURL: 'https://plato-17bc4-default-rtdb.firebaseio.com',
    storageBucket: 'plato-17bc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFdy7RsQGJ2f_BLVUOU8NdX8-dfiref0E',
    appId: '1:79067367979:ios:9e616706a3508aa619386e',
    messagingSenderId: '79067367979',
    projectId: 'plato-17bc4',
    databaseURL: 'https://plato-17bc4-default-rtdb.firebaseio.com',
    storageBucket: 'plato-17bc4.firebasestorage.app',
    iosClientId: '79067367979-n4v78n97vn5tavvl8dml1lgp22816446.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFdy7RsQGJ2f_BLVUOU8NdX8-dfiref0E',
    appId: '1:79067367979:ios:9e616706a3508aa619386e',
    messagingSenderId: '79067367979',
    projectId: 'plato-17bc4',
    databaseURL: 'https://plato-17bc4-default-rtdb.firebaseio.com',
    storageBucket: 'plato-17bc4.firebasestorage.app',
    iosClientId: '79067367979-n4v78n97vn5tavvl8dml1lgp22816446.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfbeoZviLA7AEvw9MRzBqZchRMmxHy1sY',
    appId: '1:79067367979:web:2495bc34971462e319386e',
    messagingSenderId: '79067367979',
    projectId: 'plato-17bc4',
    authDomain: 'plato-17bc4.firebaseapp.com',
    databaseURL: 'https://plato-17bc4-default-rtdb.firebaseio.com',
    storageBucket: 'plato-17bc4.firebasestorage.app',
  );
}
